### PR TITLE
Check for undefined basemap gallery thumbnail or tooltip

### PR DESCRIPTION
**Pull request by tanneryould**
When loading the Change Basemap sample, the toolkit returns the warnings below. This PR introduces a change to check if the variables are defined before passing them to the modelData, and if they are not, it passes empty strings.

```js
qrc:/esri.com/imports/Esri/ArcGISRuntime/Toolkit/Controller/BasemapGalleryController.qml:135: Error: Cannot assign [undefined] to QUrl
qrc:/esri.com/imports/Esri/ArcGISRuntime/Toolkit/Controller/BasemapGalleryController.qml:135: Error: Cannot assign [undefined] to QString
...
...
...
qrc:/esri.com/imports/Esri/ArcGISRuntime/Toolkit/Controller/BasemapGalleryController.qml:135: Error: Cannot assign [undefined] to QUrl
qrc:/esri.com/imports/Esri/ArcGISRuntime/Toolkit/Controller/BasemapGalleryController.qml:135: Error: Cannot assign [undefined] to QString
```

### CODE REVIEW

**Comment by ldanzinger** [comment]
@mfeigl can you review? Tanner hit this while testing samples

**Review by ldanzinger — CHANGES_REQUESTED** [review]
@tanneryould please open this against v.next

**Comment by mfeigl** [comment]
@tanneryould @ldanzinger Apologies, I already had fixed issue today and it's in `v.next`

**Comment by mfeigl** [comment]
https://github.com/Esri/arcgis-runtime-toolkit-qt/pull/555

**Comment by tanneryould** [comment]
@mfeigl I like the `??` notation a bit better but that's fine 😉 
Thank you! I'll go ahead and close this then.

**Pull request closed without merging**
