### PR TITLE
Have StyleButton use map as a property

### PR DESCRIPTION
**Pull request by jf990**
Changing NavigationToolbarExample to use mainMap caused the buttons to lose the reference to the map. I propose changing StyleButton to take the map as a parameter (property) instead of relying on it being a specific id

### CODE REVIEW

**Comment by ldanzinger** [comment]
@jf990 do any of the examples that use navigation toolbar need to get updated to set the map property?

**Comment by jf990** [comment]
yes, i missed it because running the sample take the toolkit from one location and the examples from a different, so the change missed the repo. I'll add it.

**Comment by ldanzinger** [comment]
I think StyleTemplateExample might also use this. Can you update any other instances of it in the example?

**Comment by jf990** [comment]
I made the correction to StyleTemplateExample and test it. I didn't find any other samples that reference it but if you notice anything else I missed LMK.

**Comment by ldanzinger** [comment]
looks good, thanks @jf990

**Pull request merged**
