### PR TITLE
changed group search icon to match ios version

### PR DESCRIPTION
**Pull request by mrwillyees**
changed group icon to match the ios version. At the moment using the same icon as the search icon. Below is a screen shot showing a different icon if preferred.
groupicons

### CODE REVIEW

**Review by anmacdonald — APPROVED** [review]
LGTM

**Review by ldanzinger — COMMENTED** [review]
Couple questions/comments for you and @anmacdonald :

* do we still need pins.svg or can it be removed?
* it seems like the icon and text are vertically top aligned vs centered aligned. 
* the icons seem oversized compared to the text, especially compared to .NET and iOS where the icons are about the same height as text, or maybe slightly smaller

**Comment by mrwillyees** [comment]
smaller icon and centered text
image

previous version:
groupicons

**Review by ldanzinger — APPROVED** [review]
LGTM

**Pull request merged**
